### PR TITLE
GitWahome

### PR DESCRIPTION
**Pull request by GitWahome**

### CODE REVIEW

**Comment by NinadKP** [comment]
I would :shipit: , but you made a mistake in the HTML of your markdown file, and you didn't use markdown syntax 😟

**Comment by NinadKP** [comment]
Now it's good 👍 

SHIP IT :shipit:

**Comment by philip-sterne** [comment]
This file is in the wrong directory.  (It's in the root directory.)

Please move the file!

**Comment by philip-sterne** [comment]
Why are there three files?  There should only be a single file in the correct directory

**Comment by GitWahome** [comment]
I presume now Its all okay prof? I must admit I was learning all this, git
includee for the first time and it wanted to get all of it done myself and
thus did a lot of trial and error. I have the basic concepts thoroughly
grasped now.

**Pull request merged**
